CREATE TABLE tb_cliente (
  id                    BIGSERIAL PRIMARY KEY,
  usuario_id            BIGINT NOT NULL REFERENCES tb_usuario(id),
  nome_negocio          VARCHAR(150) NOT NULL,
  segmento              VARCHAR(100) NOT NULL,
  cidade                VARCHAR(100),
  estado                VARCHAR(2),
  o_que_vende           TEXT,
  diferenciais          TEXT,
  horario_funcionamento VARCHAR(100),
  promocoes_fixas       TEXT,
  redes_sociais         TEXT,
  site                  VARCHAR(300),
  quantidade_posts_mes  INTEGER,
  publico_faixa_etaria  VARCHAR(50),
  publico_genero        VARCHAR(50),
  publico_classe_social VARCHAR(50),
  tom_de_voz            VARCHAR(50),
  usa_humor             BOOLEAN DEFAULT FALSE,
  cores_principais      VARCHAR(200),
  estilo_visual         TEXT,
  observacoes_livres    TEXT,
  ativo                 BOOLEAN DEFAULT TRUE,
  criado_em             TIMESTAMP DEFAULT NOW(),
  atualizado_em         TIMESTAMP
);